[package]
name = "RT"
version = "0.2.0"
edition = "2021"
authors = ["Christian Korn <c.a.konr@gmx.de>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
